# Generated by Django 4.0.4 on 2022-05-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
                ('investment', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
